on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'reason'
        required: true
        default: ''
      tags:
        description: 'forced manual rebuild'
  push:

jobs:
  local_test:
    runs-on: ubuntu-latest
    name: Self test
    steps:
      - name: Push custom label
        uses: djalal/job-status-badge@main # Uses an action in the root directory
        id: label
        with:
          cloudinary_url: ${{ secrets.CLOUDINARY_URL }}
          left_text: "hello"
          right_text: "world"
          color: "blue"
      - name: Get the label
        run: |
          echo "pushed new label on ${{ steps.label.outputs.secure_url }}"
          echo "pushed public id = ${{ steps.label.outputs.public_id }}"
          echo "pushed image bytes = ${{ steps.label.outputs.bytes }}"
